#!/bin/bash

set -e

sudo apt-get update
sudo apt-get install -y ca-certificates curl gnupg

DOCKER_KEYRING="/etc/apt/keyrings/docker.gpg"
NVIDIA_KEYRING="/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg"

sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o $DOCKER_KEYRING
sudo chmod a+r $DOCKER_KEYRING

echo "deb [arch=$(dpkg --print-architecture) signed-by=$DOCKER_KEYRING] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin nvidia-container-runtime

curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o $NVIDIA_KEYRING
curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by='$NVIDIA_KEYRING'] https://#g' | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

sudo apt-get update
sudo apt-get install -y nvidia-container-runtime

sudo docker login
sudo groupadd docker
sudo usermod -aG docker $USER
#sudo newgrp docker

DOCKER_CONFIG_DIR="/home/$USER/.docker"
sudo mkdir -p $DOCKER_CONFIG_DIR
sudo chown $USER:$USER $DOCKER_CONFIG_DIR -R
sudo chmod g+rwx "$HOME/.docker" -R

sudo systemctl enable docker.service
sudo systemctl enable containerd.service
sleep 5
sudo chmod 666 /var/run/docker.sock